[versions]
kotlin = "2.0.0"
ktlint = "1.2.1"
detekt = "1.23.6"
junit = "5.10.2"

[libraries]
ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlint" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }
ktlint-cli-ruleset-core = { module = "com.pinterest.ktlint:ktlint-cli-ruleset-core", version.ref = "ktlint" }
ktlint-test = { module = "com.pinterest.ktlint:ktlint-test", version.ref = "ktlint" }

detekt-core = { module = "io.gitlab.arturbosch.detekt:detekt-core", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }

junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
assertj = "org.assertj:assertj-core:3.26.0"
reflections = "org.reflections:reflections:0.10.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = "com.vanniktech.maven.publish:0.29.0"
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
shadowJar = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
